#spring.application.name=smart-study-platform
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study_platform?useSSL=false&serverTimezone=UTC
    username: root
    password: Sharanu@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: SmartStudyPlatform

server:
  port: 8080
